const ResponseCodes = Object.freeze({

    SUCCESS: "SUCCESS",

    VALIDATION_ERROR: "VALIDATION_ERROR",
    
    INVALID_ROLE: "INVALID_ROLE",

    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

    UNAUTHORIZED: "UNAUTHORIZED",

    FORBIDDEN: "FORBIDDEN",

    NOT_FOUND: "NOT_FOUND",

    DUPLICATE_RECORD: "DUPLICATE_RECORD",

    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"

});

module.exports = {
    ResponseCodes
};