const seedData = {
  users: [
    {
      id: "usr_customer_1",
      name: "Rakesh Jaiswal",
      mobile: "9876543210",
      password: "123456",
      selectedRole: null,
      city: "Delhi",
    },
    {
      id: "usr_traveller_1",
      name: "Aman Kumar",
      mobile: "9999999999",
      password: "123456",
      selectedRole: null,
      city: "Delhi NCR",
    },
  ],
  sessions: [],
  travellers: [
    {
      id: "trav_1",
      name: "Aman Kumar",
      rating: "4.8",
      route: "Delhi NCR -> Jaipur",
      vehicle: "Car",
      priceRange: "Rs 220 - Rs 520",
      status: "Available",
      slots: 3,
    },
    {
      id: "trav_2",
      name: "Neha Sharma",
      rating: "4.9",
      route: "Gurugram -> Chandigarh",
      vehicle: "Shatabdi Train",
      priceRange: "Rs 250 - Rs 650",
      status: "Available",
      slots: 2,
    },
    {
      id: "trav_3",
      name: "Rahul Verma",
      rating: "4.7",
      route: "Noida -> Agra",
      vehicle: "SUV",
      priceRange: "Rs 180 - Rs 420",
      status: "1 slot left",
      slots: 1,
    },
    {
      id: "trav_4",
      name: "Simran Kaur",
      rating: "4.9",
      route: "Jaipur -> Udaipur",
      vehicle: "Volvo Bus",
      priceRange: "Rs 240 - Rs 580",
      status: "Available",
      slots: 4,
    },
    {
      id: "trav_5",
      name: "Vikram Singh",
      rating: "4.6",
      route: "Delhi -> Lucknow",
      vehicle: "Train",
      priceRange: "Rs 280 - Rs 720",
      status: "KYC verified",
      slots: 2,
    },
  ],
  parcels: [
    {
      id: "par_1",
      title: "Laptop sleeve and charger",
      senderName: "Rakesh Jaiswal",
      receiverName: "Mohit Jain",
      pickup: "Connaught Place, New Delhi",
      drop: "C-Scheme, Jaipur",
      weight: "1.8 kg",
      payout: "Rs 460",
      badge: "Verified",
      note: "Office item, pickup from reception before 2:00 PM",
      pickupOtp: "4921",
      deliveryOtp: "8150",
      status: "Available",
      customerId: "usr_customer_1",
      travellerId: null,
    },
    {
      id: "par_2",
      title: "Prescription medicine pack",
      senderName: "Priya Mehta",
      receiverName: "Anjali Mehta",
      pickup: "Sector 29, Gurugram",
      drop: "Vaishali Nagar, Jaipur",
      weight: "0.8 kg",
      payout: "Rs 340",
      badge: "Urgent",
      note: "Keep away from direct sunlight, deliver same day",
      pickupOtp: "3814",
      deliveryOtp: "6629",
      status: "Available",
      customerId: "usr_customer_1",
      travellerId: null,
    },
    {
      id: "par_3",
      title: "CA documents envelope",
      senderName: "Nitin Bansal",
      receiverName: "Sharma Associates",
      pickup: "Noida Sector 62",
      drop: "MI Road, Jaipur",
      weight: "0.3 kg",
      payout: "Rs 260",
      badge: "Envelope",
      note: "Do not fold, hand over to office desk",
      pickupOtp: "1492",
      deliveryOtp: "7741",
      status: "Accepted",
      customerId: "usr_customer_1",
      travellerId: "usr_traveller_1",
    },
    {
      id: "par_4",
      title: "Wedding gift hamper",
      senderName: "Kavita Soni",
      receiverName: "Sonia Agarwal",
      pickup: "Karol Bagh, Delhi",
      drop: "Bapu Bazaar, Jaipur",
      weight: "2.6 kg",
      payout: "Rs 540",
      badge: "Fragile",
      note: "Glass item inside, keep upright",
      pickupOtp: "2455",
      deliveryOtp: "9861",
      status: "Available",
      customerId: "usr_customer_1",
      travellerId: null,
    },
    {
      id: "par_5",
      title: "Exam admit card packet",
      senderName: "Deepak Yadav",
      receiverName: "Rohit Yadav",
      pickup: "Rajouri Garden, Delhi",
      drop: "Sector 17, Chandigarh",
      weight: "0.2 kg",
      payout: "Rs 300",
      badge: "Priority",
      note: "Important document, call receiver before delivery",
      pickupOtp: "6332",
      deliveryOtp: "4208",
      status: "Available",
      customerId: "usr_customer_1",
      travellerId: null,
    },
  ],
  trips: [
    {
      id: "trip_1",
      travellerId: "usr_traveller_1",
      from: "Delhi",
      to: "Jaipur",
      time: "Today, 11:30 AM",
      distance: "281 km",
      matches: "4 matching parcels",
      status: "Active",
    },
    {
      id: "trip_2",
      travellerId: "usr_traveller_1",
      from: "Jaipur",
      to: "Udaipur",
      time: "Tomorrow, 8:00 AM",
      distance: "395 km",
      matches: "2 matching parcels",
      status: "Scheduled",
    },
    {
      id: "trip_3",
      travellerId: "usr_traveller_1",
      from: "Delhi",
      to: "Chandigarh",
      time: "Wed, 6:45 AM",
      distance: "244 km",
      matches: "1 matching parcel",
      status: "Scheduled",
    },
    {
      id: "trip_4",
      travellerId: "usr_traveller_1",
      from: "Noida",
      to: "Agra",
      time: "Fri, 7:20 AM",
      distance: "190 km",
      matches: "1 matching parcel",
      status: "Completed",
    },
  ],
  deliveries: [
    {
      id: "del_1",
      parcelId: "par_2",
      parcel: "Prescription medicine pack",
      route: "Sector 29, Gurugram to Vaishali Nagar, Jaipur",
      state: "Picked up",
      meta: "ETA 7:45 PM, temperature safe pouch verified",
      progress: 55,
      nextAction: "Mark in transit",
      earning: "Rs 340",
    },
    {
      id: "del_2",
      parcelId: "par_1",
      parcel: "Laptop sleeve and charger",
      route: "Connaught Place, New Delhi to C-Scheme, Jaipur",
      state: "Booked",
      meta: "Waiting for traveller",
      progress: 15,
      nextAction: "Book traveller",
      earning: "Rs 460",
    },
    {
      id: "del_3",
      parcelId: "par_3",
      parcel: "CA documents envelope",
      route: "Noida Sector 62 to MI Road, Jaipur",
      state: "Accepted",
      meta: "Pickup OTP 1492 shared with sender",
      progress: 30,
      nextAction: "Verify pickup",
      earning: "Rs 260",
    },
    {
      id: "del_4",
      parcelId: "par_6",
      parcel: "Books parcel",
      route: "Delhi University North Campus to Kota Hostel Area",
      state: "Delivered",
      meta: "Delivered at 6:35 PM, payment released",
      progress: 100,
      nextAction: "View receipt",
      earning: "Rs 390",
    },
  ],
};

module.exports = { seedData };
